const categories = [
    {
      id: '1',
      title: 'Baking',
      ingredients: [
        'Baking Powder',
        'Baking Soda',
        'Yeast',
        'Cream of Tartar',
        'White Sugar',
        'Brown Sugar',
        'Powdered Sugar',
        'Honey',
        'Maple Syrup',
        'Molasses',
        'Agave Nectar',
        'Unsweetened Chocolate',
        'Semisweet Chocolate',
        'Bittersweet Chocolate',
        'White Chocolate',
        'Cocoa Powder',
        'Unsweetened Cocoa Powder',
        'Dutch-Process Cocoa Powder',
        'Vanilla Extract',
        'Almond Extract',
        'Lemon Extract',
        'Orange Extract',
        'Peppermint Extract',
        'Coconut Extract',
        'Maple Extract',
        'Anise Extract',
        'Rum Extract',
        'Coffee Extract',
        'Rose Water',
        'Baking Chocolate',
        'Unsweetened Chocolate',
        'Candied Fruit',
        'Candied Ginger',
        'Dried Fruit',
        'Raisins',
        'Citrus Zest',
        'Nuts',
        'Coconut',
        'Oats',
        'Spices',
        'Herbs',
        'Marshmallows',
        'Pretzels',
        'Graham Crackers',
        'Vanilla Beans',
        'Vanilla Bean Paste',
        'Food Coloring'
      ]
    },
    {
      id: '2',
      title: 'Dairy',
      ingredients: [
        'Milk',
        'Cream',
        'Yogurt',
        'Cottage Cheese',
        'Sour Cream',
        'Ricotta Cheese',
        'Mozzarella Cheese',
        'Swiss Cheese',
        'Parmesan Cheese',
        'Cream Cheese',
        'Gouda Cheese',
        'Feta Cheese',
        'Gruyere Cheese',
        'Cheddar Cheese',
        'Butter',
        'Ice Cream',
        'Whipped Cream',
        'Condensed Milk',
        'Evaporated Milk',
        'Half-and-Half',
        'Kefir',
        'Whey',
        'Quark',
        'Buttermilk',
        'Blue Cheese',
        'Heavy Cream',
        'Sour Cream',
    ]

    },
    {
      id: '3',
      title: 'Meats and Seafoods',
      ingredients: [
        'Beef pieces',
        'Chuck Roast',
        'Sirloin Steak',
        'Ribeye Steak',
        'Ground Beef',
        'Short Ribs',
        'Pork pieces',
        'Pork Chops',
        'Pork Tenderloin',
        'Pork Shoulder',
        'Bacon',
        'Ham',
        'Chicken pieces',
        'Chicken Breasts',
        'Chicken Thighs',
        'Chicken Wings',
        'Chicken Drumsticks',
        'Chicken Livers',
        'Lamb pieces',
        'Lamb Chops',
        'Lamb Shoulder',
        'Lamb Shank',
        'Ground Lamb',
        'Lamb Ribs',
        'Veal pieces',
        'Veal Cutlets',
        'Veal Roast',
        'Veal Shank',
        'Veal Scaloppini',
        'Ground Veal',
        'Venison',
        'Bison',
        'Rabbit',
        'Duck',
        'Goose',
        'Pheasant',
        'Quail',
        'Cornish Hen',
        'Ostrich',
        'Bacon',
        'Sausage',
        'Ham',
        'cod',
        'salmon',
        'halibut',
        'haddock',
        'swordfish',
        'sardines',
        'anchovies',
        'tuna',
        'trout',
        'mackerel',
        'pike',
        'pollock',
        'catfish',
        'perch',
        'tilapia',
        'carp',
        'flounder',
        'grouper',
        'red snapper',
        'mahi mahi',
        'barramundi',
        'monkfish',
        'crabs',
        'crayfish',
        'shrimp',
        'lobster',
        'scallops',
        'clams',
        'mussels',
        'oysters',
        'squid',
        'octopus',
        'cuttlefish',
        'squids',
        'octopuses',
        'sea urchins',
        'sea cucumbers',
        'abalone',
        'conch',
        'snails',
        'whelks',
        'scallop roe',
        'caviar',
        'krill',
        'sea beans',
        'sea lettuce',
        'sea moss'
        ]
    },
    {
      id: '4',
      title: 'Fruits',
      ingredients: [
        'Apple',
        'Apricot',
        'Avocado',
        'Banana',
        'Blackberry',
        'Blueberry',
        'Cantaloupe',
        'Cherry',
        'Clementine',
        'Coconut',
        'Cranberry',
        'Date',
        'Dragon fruit',
        'Durian',
        'Fig',
        'Gooseberry',
        'Grape',
        'Grapefruit',
        'Honeydew',
        'Jackfruit',
        'Kiwi',
        'Kumquat',
        'Lemon',
        'Lime',
        'Lychee',
        'Mango',
        'Melon',
        'Mulberry',
        'Nectarine',
        'Orange',
        'Papaya',
        'Passion fruit',
        'Peach',
        'Pear',
        'Pineapple',
        'Plum',
        'Pomegranate',
        'Quince',
        'Raspberry',
        'Star fruit',
        'Strawberry',
        'Tangerine',
        'Tomato',
        'Watermelon'
      ]
    },
    {
      id: '5',
      title: 'Vegetables',
      ingredients: [
        'Artichoke',
        'Asparagus',
        'Bean Sprouts',
        'Beetroot',
        'Bell Pepper',
        'Bok Choy',
        'Broccoli',
        'Brussels Sprouts',
        'Cabbage',
        'Carrot',
        'Cauliflower',
        'Celery',
        'Chili Pepper',
        'Collard Greens',
        'Corn',
        'Cucumber',
        'Daikon',
        'Dill',
        'Eggplant',
        'Fennel',
        'Garlic',
        'Ginger',
        'Green Beans',
        'Hearts of Palm',
        'Horseradish',
        'Kale',
        'Kohlrabi',
        'Leeks',
        'Lettuce',
        'Mushrooms',
        'Mustard Greens',
        'Okra',
        'Onion',
        'Parsnip',
        'Peas',
        'Potato',
        'Pumpkin',
        'Radicchio',
        'Radish',
        'Rhubarb',
        'Scallions',
        'Shallot',
        'Spinach',
        'Sweet Potato',
        'Tomato',
        'Turnip',
        'Vidalia Onion',
        'Zucchini'
      ]
    },
    {
      id: '6',
      title: 'Fats and Oils',
      ingredients: [
        'Almond Oil',
        'Avocado Oil',
        'Canola Oil',
        'Coconut Oil',
        'Flaxseed Oil',
        'Ghee',
        'Grape Seed Oil',
        'Hazelnut Oil',
        'Hemp Oil',
        'Lard',
        'Macadamia Oil',
        'Olive Oil',
        'Palm Oil',
        'Peanut Oil',
        'Rice Bran Oil',
        'Safflower Oil',
        'Sesame Oil',
        'Shea Butter',
        'Sunflower Oil',
        'Walnut Oil'
      ]
    },
    {
        id: '7',
        title: 'Nuts and Seeds',
        ingredients: [
            'Almonds',
            'Brazil Nuts',
            'Cashews',
            'Hazelnuts',
            'Macadamia Nuts',
            'Pecans',
            'Pine Nuts',
            'Pistachios',
            'Walnuts',
            'Chia Seeds',
            'Flax Seeds',
            'Hemp Seeds',
            'Pumpkin Seeds',
            'Sesame Seeds',
            'Sunflower Seeds'
        ]
      },
      {
        id: '8',
        title: 'Legumes',
        ingredients: [
            'Adzuki Beans',
            'Black Beans',
            'Black-eyed Peas',
            'Chickpeas (Garbanzo Beans)',
            'Fava Beans',
            'Great Northern Beans',
            'Kidney Beans',
            'Lentils',
            'Lima Beans',
            'Mung Beans',
            'Navy Beans',
            'Pigeon Peas',
            'Red Beans',
            'Soybeans',
            'Split Peas',
            'Urad Dal',
            'Toor Dal (Yellow Split Peas)',
            'Masoor Dal (Red Lentils)',
            'Moong Dal (Green Split Peas)',
            'Chana Dal (Split Chickpeas)',
            'Rajma (Kidney Beans)',
            'Kala Chana (Black Chickpeas)',
            'Horse Gram',
            'Field Beans (Avarekai)'
          ]
      },
      {
        id: '9',
        title: 'Grains',
        ingredients:  [
            'All-Purpose Flour',
            'Whole Wheat Flour',
            'Almond Flour',
            'Gluten-Free Flour',
            'Cake Flour',
            'Bread Flour',
            'Rye Flour',
            'Oat Flour',
            'Cornmeal',
            'Semolina',
            'Polenta',
            'Buckwheat Flour',
            'Tapioca Flour',
            'Coconut Flour',
            'Rice Flour',
            'Quinoa Flour',
            'Amaranth Flour',
            'Barley Flour'
        ]
      },
      {
        id: '10',
        title: 'Spices',
        ingredients:[
            'Allspice',
            'Anise',
            'Caraway',
            'Cardamom',
            'Celery seed',
            'Chili powder',
            'Cinnamon',
            'Cloves',
            'Coriander',
            'Cumin',
            'Curry powder',
            'Fennel',
            'Garlic powder',
            'Ginger',
            'Mustard powder',
            'Nutmeg',
            'Onion powder',
            'Paprika',
            'Pepper',
            'Poppy seed',
            'Rosemary',
            'Saffron',
            'Sage',
            'Salt',
            'Tarragon',
            'Thyme',
            'Turmeric'
        ]
      },
  ];
  
  export default categories;
  